spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/n3-teste
    username: postgres
    password: abc101
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8090